### ISSUE TITLE
Garbage Collection Count no data

### ISSUE THREAD

**Issue by linyy2233** [crab86/grafana-plei#2]
![image](https://user-images.githubusercontent.com/39547259/48122194-f1494600-e2b1-11e8-8d10-54823075fc2c.png)

can you help me see 一 see.

**Comment by crab86** [comment]
Is this the only graph that is not working for you? Did you set the datasource to your .monitoring-es Index?

**Comment by linyy2233** [comment]
https://github.com/grafana/grafana/issues/11175
This solved my problem，thanks.

**Comment by crab86** [comment]
Okay, but out-of-the-box my dashboard does not use "count" as metric type. For GC Count (as for most of the graphs) it uses an derivative of an average metric. And it works great: 

![garbage_collection_count](https://user-images.githubusercontent.com/20257828/48184962-ed5e0800-e333-11e8-88bc-7b2384c48529.jpg)

![garbage_collection_count_metrics](https://user-images.githubusercontent.com/20257828/48185061-33b36700-e334-11e8-9689-0c167efe69b4.jpg)

Anyway, i am closing this issue.

**Comment by linyy2233** [comment]
![image](https://user-images.githubusercontent.com/39547259/48187384-e48e2600-e375-11e8-85eb-5a4396a892ef.png)
It should be a minute here.
Thank you very much for providing such a useful template.

**Comment by crab86** [comment]
This actually depends on the interval you set as "xpack.monitoring.collection.interval" in your elasticsearch.yml as stated here:

[Monitoring Settings in Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/monitoring-settings.html)

Per default this is 10s, if you changed it to 1min, then yes it makes sense to set the min time interval to 1m :) I'm glad when the template is useful for you 👍
